Sara Aljaafari - 169044425
CP421 Assignment 2

In [6]:
#QUESTION 1
import pandas as pd
retail=pd.read_excel("Online Retail.xlsx")
retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [8]:
cleaned_retail=retail.dropna(subset=['CustomerID','StockCode'])
cleaned_retail= cleaned_retail[cleaned_retail['Quantity']>0]
nonproduct=["BANK CHARGES","C2", "DOT","M","PADS", "POST"]
cleaned_retail=cleaned_retail[~cleaned_retail['StockCode'].astype(str).isin(nonproduct)]
#display(cleaned_retail)

transactional=cleaned_retail.groupby('InvoiceNo')['StockCode'].apply(set).reset_index()
transactional.set_index('InvoiceNo',inplace=True)
binary_matrix=transactional.explode('StockCode').reset_index()
binary_matrix['Presence']= 1
binary_matrix=binary_matrix.pivot(index='InvoiceNo',columns='StockCode',values='Presence').fillna(0)
binary_matrix=binary_matrix.astype(int)
display(binary_matrix)

StockCode,10002,10080,10120,10125,10133,10135,11001,15030,15034,15036,...,90214O,90214P,90214R,90214S,90214T,90214U,90214V,90214W,90214Y,90214Z
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
from itertools import combinations

transactions=[set(binary_matrix.columns[binary_matrix.iloc[i]==1]) for i in range(len(binary_matrix))]
min_sup =0.02
num_transactions=len(transactions)
def calculate_support(itemset, transactions):
    count=sum(1 for transaction in transactions if itemset.issubset(transaction))
    return count/num_transactions
item_counts={}
for transaction in transactions:
    for item in transaction:
        item_counts[item]=item_counts.get(item,0)+1
frequent_itemsets={frozenset([item]) for item, count in item_counts.items() if count/num_transactions>=min_sup}
all_frequent_itemsets={1:frequent_itemsets}
def generate_candidates(prev_frequent,k):
    candidates=set()
    prev_frequent_list=list(prev_frequent)
    for i in range(len(prev_frequent_list)):
        for j in range(i+1,len(prev_frequent_list)):
            union_set=prev_frequent_list[i]|prev_frequent_list[j]
            if len(union_set)== k:
                candidates.add(union_set)
    return candidates
k=2
while True:
    candidates=generate_candidates(frequent_itemsets,k)
    frequent_itemsets= {itemset for itemset in candidates if calculate_support(itemset,transactions)>=min_sup}
    if not frequent_itemsets:
        break
    all_frequent_itemsets[k]=frequent_itemsets
    k+=1
for k, itemsets in all_frequent_itemsets.items():
    print(f"number of frequent {k}-itemsets: {len(itemsets)}")
for k, itemsets in all_frequent_itemsets.items():
    print(f"\nfrequent {k}-itemsets:")
    for itemset in itemsets:
        print(itemset)

Number of frequent 1-itemsets: 208
Number of frequent 2-itemsets: 41
Number of frequent 3-itemsets: 1

Frequent 1-itemsets:
frozenset({22138})
frozenset({'84997D'})
frozenset({22624})
frozenset({21791})
frozenset({21523})
frozenset({21889})
frozenset({22385})
frozenset({48138})
frozenset({23301})
frozenset({22621})
frozenset({20725})
frozenset({23307})
frozenset({22487})
frozenset({22197})
frozenset({21755})
frozenset({22470})
frozenset({20971})
frozenset({22083})
frozenset({21559})
frozenset({21485})
frozenset({22147})
frozenset({22578})
frozenset({22553})
frozenset({21915})
frozenset({22328})
frozenset({22111})
frozenset({20712})
frozenset({22114})
frozenset({21754})
frozenset({20685})
frozenset({22367})
frozenset({22960})
frozenset({21524})
frozenset({22698})
frozenset({22112})
frozenset({22966})
frozenset({23202})
frozenset({85066})
frozenset({22952})
frozenset({23284})
frozenset({22557})
frozenset({71459})
frozenset({23206})
frozenset({22804})
frozenset({22417})
frozenset({22699})
frozenset({22554})
frozenset({21172})
frozenset({23198})
frozenset({22457})
frozenset({22722})
frozenset({20718})
frozenset({23356})
frozenset({22561})
frozenset({82580})
frozenset({21034})
frozenset({23200})
frozenset({21232})
frozenset({22568})
frozenset({82582})
frozenset({22865})
frozenset({22144})
frozenset({'82494L'})
frozenset({21914})
frozenset({84991})
frozenset({22659})
frozenset({22728})
frozenset({21231})
frozenset({21977})
frozenset({22427})
frozenset({21213})
frozenset({84375})
frozenset({21181})
frozenset({23199})
frozenset({22907})
frozenset({23209})
frozenset({22384})
frozenset({84879})
frozenset({22326})
frozenset({21931})
frozenset({22909})
frozenset({22750})
frozenset({22467})
frozenset({22139})
frozenset({21733})
frozenset({22356})
frozenset({82583})
frozenset({23201})
frozenset({23245})
frozenset({22697})
frozenset({23207})
frozenset({21479})
frozenset({21843})
frozenset({84077})
frozenset({82482})
frozenset({22191})
frozenset({22867})
frozenset({'84970S'})
frozenset({22386})
frozenset({84755})
frozenset({23208})
frozenset({22382})
frozenset({22178})
frozenset({22551})
frozenset({22749})
frozenset({22730})
frozenset({22149})
frozenset({48194})
frozenset({21166})
frozenset({'85123A'})
frozenset({21930})
frozenset({20726})
frozenset({21975})
frozenset({22556})
frozenset({23203})
frozenset({22666})
frozenset({22469})
frozenset({84946})
frozenset({21175})
frozenset({22961})
frozenset({22720})
frozenset({22090})
frozenset({22766})
frozenset({23439})
frozenset({21080})
frozenset({'15056N'})
frozenset({79321})
frozenset({22383})
frozenset({22193})
frozenset({82486})
frozenset({47566})
frozenset({23293})
frozenset({22150})
frozenset({22558})
frozenset({22084})
frozenset({22998})
frozenset({22727})
frozenset({23344})
frozenset({'47591D'})
frozenset({22077})
frozenset({21928})
frozenset({21174})
frozenset({22189})
frozenset({22910})
frozenset({22652})
frozenset({22617})
frozenset({20972})
frozenset({22633})
frozenset({23240})
frozenset({84378})
frozenset({85152})
frozenset({84992})
frozenset({22616})
frozenset({21929})
frozenset({21936})
frozenset({23243})
frozenset({'85099C'})
frozenset({82483})
frozenset({23322})
frozenset({23263})
frozenset({20728})
frozenset({23204})
frozenset({22667})
frozenset({20724})
frozenset({21790})
frozenset({22969})
frozenset({84380})
frozenset({20727})
frozenset({22355})
frozenset({23355})
frozenset({23300})
frozenset({23321})
frozenset({'85099B'})
frozenset({82484})
frozenset({22835})
frozenset({22411})
frozenset({22625})
frozenset({'85099F'})
frozenset({82600})
frozenset({20713})
frozenset({84836})
frozenset({22577})
frozenset({21731})
frozenset({20723})
frozenset({21621})
frozenset({22866})
frozenset({22629})
frozenset({84978})
frozenset({22630})
frozenset({22726})
frozenset({22423})
frozenset({22379})
frozenset({22555})
frozenset({22029})
frozenset({23343})
frozenset({21481})
frozenset({20914})
frozenset({22113})
frozenset({20719})
frozenset({21908})
frozenset({48187})
frozenset({23298})
frozenset({21212})
frozenset({22086})
frozenset({22993})
frozenset({23084})
frozenset({22662})
frozenset({22776})

Frequent 2-itemsets:
frozenset({23209, 20725})
frozenset({'85099B', 21931})
frozenset({20728, 20725})
frozenset({23209, 23203})
frozenset({22382, 20727})
frozenset({22384, 20725})
frozenset({22384, 22383})
frozenset({22698, 22699})
frozenset({20728, 20727})
frozenset({23209, 23206})
frozenset({21733, '85123A'})
frozenset({20725, 20726})
frozenset({23300, 23301})
frozenset({22469, 22470})
frozenset({20725, 22382})
frozenset({22382, 22383})
frozenset({20726, 22382})
frozenset({20725, 23206})
frozenset({22728, 22727})
frozenset({'85099B', '85099F'})
frozenset({22697, 22699})
frozenset({'85099B', 23203})
frozenset({22726, 22727})
frozenset({22629, 22630})
frozenset({20725, 22383})
frozenset({22699, 22423})
frozenset({22384, 20728})
frozenset({'85099B', 22411})
frozenset({22386, '85099B'})
frozenset({22086, 22910})
frozenset({23298, 47566})
frozenset({22697, 22698})
frozenset({22384, 20727})
frozenset({'85099B', 20725})
frozenset({20728, 22383})
frozenset({23202, 23203})
frozenset({20727, 22383})
frozenset({20725, 20727})
frozenset({82482, '82494L'})
frozenset({20728, 22382})
frozenset({22697, 22423})

Frequent 3-itemsets:
frozenset({22697, 22698, 22699})

In [30]:
from itertools import permutations
min_conf=0.5
association_rules=[]

for k, itemsets in all_frequent_itemsets.items():
    if k<2:
        continue
    for itemset in itemsets:
        for antecedent_size in range(1,k):
            for antecedent in combinations(itemset,antecedent_size):
                antecedent=frozenset(antecedent)
                consequent=itemset-antecedent
                support_itemset=calculate_support(itemset,transactions)
                support_antecedent =calculate_support(antecedent,transactions)
                confidence=support_itemset/support_antecedent if support_antecedent>0 else 0
                if confidence>=min_conf:
                    association_rules.append((antecedent,consequent,support_itemset,confidence))

rules_df=pd.DataFrame(association_rules,columns=['Antecedent','consequent','support','Confidence'])
rules_df=rules_df.sort_values(by='Confidence',ascending=False)
print(len(rules_df)) #total number of association rules
rules_df.head(5) #top 5 association ru,es

32

        Antecedent consequent   support  Confidence
31  (22698, 22699)    (22697)  0.021190    0.894495
29  (22697, 22698)    (22699)  0.021190    0.847826
22         (22698)    (22697)  0.024993    0.827338
2          (22698)    (22699)  0.023689    0.784173
11         (22697)    (22699)  0.029394    0.782923

In [ ]:
#QUESTION 2
column_names=["user_id","movie_id","rating","timestamp"]
ratings=pd.read_csv("ml-100k/u.data",sep="\t",names=column_names,usecols=["user_id","movie_id","rating", "timestamp"])
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [ ]:
user_counts=ratings["user_id"].value_counts()
valid_users=user_counts[user_counts>=20].index
filtered_ratings=ratings[ratings["user_id"].isin(valid_users)]

movie_counts=filtered_ratings["movie_id"].value_counts()
valid_movies= movie_counts[movie_counts>=20].index
filtered_ratings=filtered_ratings[filtered_ratings["movie_id"].isin(valid_movies)]

filtered_ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
3      244        51       2  880606923
4      166       346       1  886397596
5      298       474       4  884182806

In [32]:
ratings=ratings.sort_values(by="timestamp")
split_index=int(len(ratings)*0.8)
train_data=ratings.iloc[:split_index]
test_data=ratings.iloc[split_index:]
train_users=set(train_data["user_id"])
test_data=test_data[test_data["user_id"].isin(train_users)]

train_movies=set(train_data["movie_id"])
test_data=test_data[test_data["movie_id"].isin(train_movies)]

In [25]:
train_data.to_csv("train_data.csv",index=False) #saving it in csv for easier use
test_data.to_csv("test_data.csv",index=False) #...

In [ ]:
import numpy as np
train_data=pd.read_csv("train_data.csv")
user_item_matrix=train_data.pivot(index="user_id",columns="movie_id",values="rating").fillna(0)
matrix=user_item_matrix.values
U, sigma, Vt=np.linalg.svd(matrix,full_matrices=False)
sigma=np.diag(sigma)

def reconstruct_matrix(k):
    return np.dot(np.dot(U[:, :k], sigma[:k, :k]), Vt[:k, :])

k_values=[5,10,20,40]
reconstructed_matrices={k: reconstruct_matrix(k) for k in k_values}

predicted_matrix=pd.DataFrame(reconstructed_matrices[10],index=user_item_matrix.index, columns=user_item_matrix.columns)
def predict_rating(user_id,movie_id):
    return predicted_matrix.loc[user_id,movie_id] if movie_id in predicted_matrix.columns and user_id in predicted_matrix.index else np.nan

print(f"predicted rating: {predict_rating(5, 100):.2f}")

predicted rating: 1.14

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

test_data=pd.read_csv("test_data.csv")

def evaluate_model(k):
    reconstructed=pd.DataFrame(reconstructed_matrices[k],index=user_item_matrix.index, columns=user_item_matrix.columns)
    test_data_filtered=test_data[test_data["user_id"].isin(reconstructed.index) & test_data["movie_id"].isin(reconstructed.columns)]
    true_ratings=test_data_filtered["rating"].values
    predicted_ratings=[reconstructed.loc[u, m] for u, m in zip(test_data_filtered["user_id"],test_data_filtered["movie_id"])]
    
    rmse=np.sqrt(mean_squared_error(true_ratings,predicted_ratings))
    mae=mean_absolute_error(true_ratings,predicted_ratings)
    return rmse, mae

k_values=[5,10,20,40]
results={k: evaluate_model(k) for k in k_values}

results_df=pd.DataFrame(results,index=["RMSE", "MAE"]).T
print(results_df)

        RMSE       MAE
5   3.128440  2.911753
10  3.122529  2.898384
20  3.186081  2.957999
40  3.284962  3.054716

#discussion part b,c:

Impact of k on model performance
A lower k value leads to high reconstruction error due to excessive information loss, while a higher k captures more latent factors, reducing RMSE and MAE. However, an excessively high k can cause overfitting, where the model memorizes data rather than generalizing well. The optimal k balances accuracy and generalization.

Strengths/limitationd of matrix factorization
Matrix factorization captures hidden patterns in user preferences, handles sparse data well, and scales efficiently for large datasets, making it ideal for recommendation systems. Limitations include difficulty recommending for new users/items, requires careful tuning of k, and can be computationally expensive for very large datasets.